osx_image: xcode7.3
language: objective-c
xcode_workspace: ./Xcode-iOS/Wukong.xcworkspace
xcode_scheme: Wukong
xcode_sdk: iphonesimulator9.3
script:
  - xcodebuild [DEFAULT_OPTIONS] CODE_SIGNING_REQUIRED=NO
